
#port ??
server:
  port: 8085

#datasource
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SOCCER
    password: 1234
  devtools:
    restart:
      enabled: false
    livereload:
      enabled:
  freemarker:
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      suffix: .html
  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
    username: intectme
    password: Tnekaos3!!

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml # mappers ?? ?? ??.xml
  type-aliases-package: com.jihwan.soccer.mail.model.dto

logging:
  level:
    root: info

